### ISSUE TITLE
error when retrieving reference point in detector coordinates

### ISSUE THREAD

**Issue by skendrew** [spacetelescope/pysiaf#153]
I get an error when I try to retrieve reference point coordinates in the detector frame with pysiaf. The aperture I'm using is MIRI LRS. 

`siaf = pysiaf.Siaf('MIRI')`
`ap = siaf['MIRIM_SLIT']`
`ap.reference_point(to_frame='tel')`
(-415.069, -400.576)
`ap.reference_point(to_frame='det')`

returns the following error:

TypeError                                 Traceback (most recent call last)
<ipython-input-32-d3942359bb3c> in <module>
----> 1 ap.reference_point('det')

~/anaconda3/envs/jwst0.16.2/lib/python3.8/site-packages/pysiaf/aperture.py in reference_point(self, to_frame)
    715     def reference_point(self, to_frame):
    716         """Return the defining reference point of the aperture in to_frame."""
--> 717         return self.convert(self.V2Ref, self.V3Ref, 'tel', to_frame)
    718 
    719     # Definition of frame transforms

~/anaconda3/envs/jwst0.16.2/lib/python3.8/site-packages/pysiaf/aperture.py in convert(self, x, y, from_frame, to_frame)
    349         conversion_method = getattr(self,
    350                                     '{}_to_{}'.format(from_frame.lower(), to_frame.lower()))
--> 351         return conversion_method(x, y)
    352 
    353     def correct_for_dva(self, v2_arcsec, v3_arcsec, verbose=False):

~/anaconda3/envs/jwst0.16.2/lib/python3.8/site-packages/pysiaf/aperture.py in tel_to_det(self, *args)
   1112     def tel_to_det(self, *args):
   1113         """Telescope to detector frame transformation."""
-> 1114         return self.sci_to_det(*self.idl_to_sci(*self.tel_to_idl(*args)))
   1115 
   1116     def raw_to_sci(self, x_raw, y_raw):

~/anaconda3/envs/jwst0.16.2/lib/python3.8/site-packages/pysiaf/aperture.py in idl_to_sci(self, x_idl, y_idl)
   1087     def idl_to_sci(self, x_idl, y_idl):
   1088         """Ideal to science frame transformation."""
-> 1089         x_model, y_model = self.distortion_transform('idl', 'sci')
   1090         return x_model(x_idl, y_idl), y_model(x_idl, y_idl)
   1091 

~/anaconda3/envs/jwst0.16.2/lib/python3.8/site-packages/pysiaf/aperture.py in distortion_transform(self, from_system, to_system, include_offset)
    800 
    801         # degree of distortion polynomial
--> 802         degree = np.int(getattr(self, 'Sci2IdlDeg'))
    803 
    804         number_of_coefficients = polynomial.number_of_coefficients(degree)

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by Johannes-Sahlmann** [comment]
'MIRIM_SLIT' is an aperture of type SLIT for which the polynomial coefficients and hence the Sci2IdlDeg attribute are not defined. (Probably this error should be caught with a respective message).

**Comment by skendrew** [comment]
ok thanks @Johannes-Sahlmann. I will retrieve in v2v3 coordinates and then do the conversion.
