### ISSUE TITLE
JWST PRD Version Mismatch 

### ISSUE THREAD

**Issue by AarynnCarter** [spacetelescope/pysiaf#189]
Hi,

I've been using Pandeia recently and have been running into a warning repeatedly when the pysiaf dependency is used (see below). Upon performing the pip install / conda update commands the warning does not go away, and I can't seem to get the PRD version to match. 

Could someone provide guidance on how to ensure these versions match up? Additionally, are there any significant drawbacks from using PRDOPSSOC-034 vs PRDOPSSOC-036?

Cheers,
Aarynn

```
**WARNING**: LOCAL JWST PRD VERSION PRDOPSSOC-034 DOESN'T MATCH THE CURRENT ONLINE VERSION PRDOPSSOC-036
Please consider updating pysiaf, e.g. pip install --upgrade pysiaf or conda update pysiaf

```

**Comment by Witchblade101** [comment]
This was due to the end of support for Travis CI at the Institute, requiring a move to GitHub actions. The infrastructure for that was just approved today, so hopefully we'll have this resolved soon.

**Comment by AarynnCarter** [comment]
Okay good to know, thanks for the quick response!

**Comment by Witchblade101** [comment]
This should be fixed as of this morning:

In [1]: import pysiaf

In [2]: print(pysiaf.JWST_PRD_VERSION)
PRDOPSSOC-036

**Comment by AarynnCarter** [comment]
Can confirm, things seem to be working on my end now when installing from Github!
