### ISSUE TITLE
Consider transitioning to setuptools_scm

### ISSUE THREAD

**Issue by jhunkeler** [spacetelescope/pysiaf#210]
I wrote `relic` as a replacement for `stsci.distutils` a couple years before other versioning solutions hit the mainstream. At this time `relic` is considered dead software. I was its sole maintainer and at this point hasn't been updated/touched in a very long time. I suggest replacing it in your project with something like `setuptools_scm` as soon as possible.

https://pypi.org/project/setuptools-scm/

cc @shanosborne @kjbrooks

**Comment by Witchblade101** [comment]
Thanks! We will look into it.

**Comment by Witchblade101** [comment]
Done in Issue #231
