### ISSUE TITLE
Need to add option for off-nominal GWA tilts to NIRSpec transforms

### ISSUE THREAD

**Issue by charlesrp** [spacetelescope/pysiaf#22]
NIRSpec SIAF transforms that cross the Grating Wheel Assembly Mirror should take
optional arguments gwa_ytil and gwa_xtil that are used to specify the GWA sensor
positions. If these are not specified gwa_ytil should default to rx0 as defined
in the SIAF gwa transform rows, while gwa_xtil should default to ry0

The coefficients AX, AY, rx0, and ry0 as read from the SIAF file columns
XSciScale, YSciScale, XSciRef, and YSciRef in the GWA_OTE transform rows. 

The user should normally just specify something like either xsci, ysci =
nrs1.tel_to_sci(v2,v3) as they do now to get the default tilts, or xsci, ysci =
nrs1.tel_to_sci(v2,v3, gwa_ytil=value1, gwa_xtil=value2 ) and have the supplied
coefficients used in any transformation that crosses the GWA.  If the input
coordinates are arrays of values, the gwa_ytil and gwa_xtil should be able to
take either single scalar values or matching length arrays.

It should be allowed to supply tilt values for any NIRSpec transform, although
of course it will only have an effect on transforms that cross the GWA.

A version of the transformation equations in both directions taken from python
code written by Maria Pena and based on IDL code from Tony Keyes is given below.
The original equations are based on NTN-2014-005/ESA-JWST-TN-21403 "Geometrical
transforms for NIRSpec target acquisition" by G. Giardino, P. Ferruit, C. Alves
de Oliveira These have the advantage that they've been tested for both
directions, although the notation does vary from that needed in pysiaf.

The sample code below hard-wires the SIAF coefficients in as defaults. In the actual pysiaf code these  should of course be set  up to simply use the SIAF table values, and the tilt parameters 
should  default to the values that yield zero for delta theta (gwa_xtil defaults to ry0 and
gwa_ytil defaults to rx0). Other changes to this code will be needed to conform to pysiaf naming
and conventions.

def gwain_to_gwaout(xgwa_in, ygwa_in, gwa_xtil, gwa_ytil, ax=4260.830, ay=-9108.782, rx0=0.196614012122, ry0=0.347495883703):
    ''' Implementation of reflection in GWA pupil plane accross mirror as a function of the GWA tilt sensor angles
    This is for the direction from the detector towards the sky, where xgwa/ygwa is the coordinate system before
    the reflection, while xgwa_out/ygwa_out is the coordinate system after the reflection.  The equations here are valid
    in the small angle approximation and are based on NTN-2014-005/ESA-JWST-TN-21403 Geometrical transforms for
    NIRSpec target acquisition by G. Giardino, P. Ferruit, C. Alves de Oliveira.
        For this test code we are supplying specific default values for the SIAF coefficients. In production code these 
    should be taken from the SIAF file.  Also in production code, gwa_xtil, if not specified, should default to ry0 
    and gwa_ytil to rx0 (note the x/y swap in these definitions.)

    inputs: xgwa - mirror rotation angle in 'X' direction (units arc-sec)
            ygwa - mirror rotation angle in 'Y' direction  (units arc-sec)
            gwa_xtil (units mV) - gwa_xtil telemetry measurement
            gwa_ytil (units mV) - gwa_ytil telemetry measurement
            ax (arc-sec/mV)  - from XSciScale column in GWA_OTE transform rows
            ay (arc-sec/mV)  - from YSciScale column in GWA_OTE transform rows
            rx0 (mV)  # nominal GWA sensor value - from XSciRef in GWA_OTE rows
            ry0 (mV)  # nominal GWA sensor value - from YSciRef in GWA_OTE rows
    outputs: xgwa_out, ygwa_out - GWA angular coordinates after reflection and rotation.

    initial IDL version - T. Keyes 2015
    initial python version M. Pena-Guerrero 2015 in ct_forward function in coords_transform.py in nirspec_TA module
    revised C. Proffitt 2018 to isolate gwa transforms and simplify code and notation.
    '''  
    delta_theta_x = 0.5 * ax * (gwa_ytil - rx0) * np.pi / (180. * 3600.0)
    delta_theta_y = 0.5 * ay * (gwa_xtil - ry0) * np.pi / (180. * 3600.0)
    
    # calculate direction cosines of xgwa, ygwa
    v = np.abs(np.sqrt(1.0 + xgwa*xgwa + ygwa*ygwa))
    x0 = xgwa_in / v
    y0 = ygwa_in / v
    z0 = 1.0 / v
    # rotate to mirror reference system with small angle approx. and perform rotation
    x1 = -1 * (x0 - delta_theta_y * np.sqrt(1.0 - x0*x0 - (y0+delta_theta_x*z0)*(y0+delta_theta_x*z0)))
    y1 = -1 * (y0 + delta_theta_x * z0)
    z1 = np.sqrt(1.0 - x1*x1 - y1*y1)
    # rotate reflected ray back to ref GWA coord system with small angle approx., 
    # but first with an inverse rotation around the y-axis
    x2 = x1 + delta_theta_y * z1
    y2 = y1
    z2 = np.sqrt(1.0 - x2*x2 - y2*y2)
    # now do an inverse rotation around the x-axis
    x3 = x2
    y3 = y2 - delta_theta_x * z2     
    z3 = np.sqrt(1.0 - x3*x3 - y3*y3)
    # compute the cosines from direction cosines
    xgwa_out = x3 / z3
    ygwa_out = y3 / z3
 
    return xgwa_out, ygwa_out
    
def gwaout_to_gwain(xgwa_out, ygwa_out, gwa_xtil, gwa_ytil, ax=4260.830, ay=-9108.782, rx0=0.196614012122, ry0=0.347495883703):

    delta_theta_x = 0.5 * ax * (gwa_ytil - rx0) * np.pi / (180. * 3600.0)
    delta_theta_y = 0.5 * ay * (gwa_xtil - ry0) * np.pi / (180. * 3600.0)
    
    # calculate direction cosines of xt, yt, (xgwa, ygwa)   
    v = np.abs(np.sqrt(1.0 + xgwa_out*xgwa_out + ygwa_out*ygwa_out))
    x3 = xgwa_out / v
    y3 = ygwa_out / v
    z3 = 1.0 / v
    # do inverse rotation around the x-axis
    x2 = x3
    y2 = y3 + delta_theta_x*z3
    z2 = np.sqrt(1.0 - x2*x2 - y2*y2)
    # rotate to mirror reference system with small angle approx. and perform rotation
    x1 = x2 - delta_theta_y*z2 # try changing - to +???
    y1 = y2
    z1 = np.sqrt(1.0 - x1*x1 - y1*y1)
    # rotate reflected ray back to reference GWA coordinate system (use small angle approx.),
    # first with an inverse rotation around the y-axis:
    x0 = -1.0*x1 + delta_theta_y * np.sqrt(1.0 - x1*x1 - (y1+delta_theta_x*z1)*(y1+delta_theta_x*z1))
    y0 = -1.0*y1 - delta_theta_x*z1
    z0 = np.sqrt(1.0 - x0*x0 - y0*y0)
    
    xgwa_in = x0/z0
    ygwa_in = y0/z0

    return xgwa_in, ygwa_in

**Comment by Johannes-Sahlmann** [comment]
@charlesrp Let's meet in person to discuss the plan for implementation?

**Comment by charlesrp** [comment]
I have a branch that has implemented the tilt dependent gwa transformations and also @Johannes-Sahlmann 's suggestion that the tilt and filter_name should be fields in the aperture object rather than passed as function parameters. I've also modified the tests to use the non-default tilt parameters. But there are still a few issues with my implementation should be discussed with @Johannes-Sahlmann prior to sending the pull request. - Charles

**Comment by Johannes-Sahlmann** [comment]
Please push your branch to origin (https://github.com/charlesrp), so I will be able to have a look at your changes.
