### ISSUE TITLE
Update HST SIAF

### ISSUE THREAD

**Issue by sean-lockwood** [spacetelescope/pysiaf#291]
Looks like we're missing 9 HST updates after SCI-510 (03/25/16) affecting COS, ACS, & FGS.

https://github.com/spacetelescope/pysiaf/tree/master/pysiaf/prd_data/HST

**Comment by Witchblade101** [comment]
We are pretty much completely in the dark regarding HST SIAF updates. Any tips on where to look to find out what is missing, or who we should talk to?

**Comment by sean-lockwood** [comment]
I'm slacking you the link.
