### ISSUE TITLE
add unit tests for rotations.py

### ISSUE THREAD

**Issue by Johannes-Sahlmann** [spacetelescope/pysiaf#3]

**Comment by Johannes-Sahlmann** [comment]
see https://github.com/spacetelescope/pysiaf/blob/master/pysiaf/tests/test_projection.py

**Comment by ColinRCox** [comment]
I do have docstrings, i.e. stuff between triple quotes for most things. I can expand these.
I will also give descriptions of the input and output variables.
I will do this as a first stage before inventing the tests.

**Comment by Johannes-Sahlmann** [comment]
Sounds good. Please see https://github.com/spacetelescope/style-guides/blob/master/guides/python.md for guidelines

**Comment by ColinRCox** [comment]
That link gave me a 404 error

Colin Cox
cox@stsci.edu<mailto:cox@stsci.edu>



On Aug 23, 2018, at 4:04 PM, Johannes Sahlmann <notifications@github.com<mailto:notifications@github.com>> wrote:


Sounds good. Please see https://github.com/spacetelescope/style-guides/blob/master/guides/python.md for guidelines

**Comment by Johannes-Sahlmann** [comment]
Oh. That is because you are not recognized as part of the STScI organisation on github.

@stscicrawford can you please add @ColinRCox to stsci on github?

**Comment by stscicrawford** [comment]
@ColinRCox -- you should have an invitation and then be able to see the page.   Let me know if you have any other questions.

**Comment by ColinRCox** [comment]
That does not seem to make any difference. Is there something I should do?

Colin Cox
cox@stsci.edu<mailto:cox@stsci.edu>



On Aug 23, 2018, at 4:41 PM, Steve Crawford <notifications@github.com<mailto:notifications@github.com>> wrote:


@ColinRCox<https://github.com/ColinRCox> -- you should have an invitation and then be able to see the page. Let me know if you have any other questions.

**Comment by Johannes-Sahlmann** [comment]
@ColinRCox you should have received an invitation email that you have to accept. I also added you to the SIAF team on github for which you should have received a separate invitation email.
Can you please confirm?

**Comment by stscicrawford** [comment]
Hi Collin -- sorry I had to add you to one more list and not just the organization.   Hopefully you should have access now.

**Comment by ColinRCox** [comment]
Thank you.It is working now.

Colin Cox
cox@stsci.edu<mailto:cox@stsci.edu>



On Aug 23, 2018, at 7:41 PM, Steve Crawford <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Collin -- sorry I had to add you to one more list and not just the organization. Hopefully you should have access now.
