### ISSUE TITLE
update to PRDOPSSOC-M-025

### ISSUE THREAD

**Issue by Johannes-Sahlmann** [spacetelescope/pysiaf#94]
The SIAF changes made for PRDOPSSOC-M-024 have been reverted and PRDOPSSOC-M-025 was released. 

pysiaf has to ingest and default to PRDOPSSOC-M-025.

The procedure to follow is described here:
https://innerspace.stsci.edu/pages/viewpage.action?pageId=107324779

**Comment by shanosborne** [comment]
This issue was closed by #96 and the new release of `pysiaf` was added to `pypi` and `astroconda-contrib`.
